apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedroribeiro-playlist-recommender-deployment
  labels:
    app: pedroribeiro-playlist-recommender-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pedroribeiro-playlist-recommender-pod
  template:
    metadata:
      labels:
        app: pedroribeiro-playlist-recommender-pod
    spec:
      containers:
      - name: api-container
        image: pdrgbr/flask-api:0.2
        ports:
        - containerPort: 32210
        volumeMounts:
        - name: project2-pv-pedroribeiro
          mountPath: /home/pedroribeiro/project2-pv
      - name: gerador-container
        image: pdrgbr/playlists-recommender:0.4
        volumeMounts:
        - name: project2-pv-pedroribeiro
          mountPath: /home/pedroribeiro/project2-pv
      terminationGracePeriodSeconds: 900
