apiVersion: batch/v1
kind: Job
metadata:
  name: gerador-job
spec:
  template:
    spec:
      containers:
      - name: gerador-container
        image: pdrgbr/playlists-recommender:0.4
        volumeMounts:
        - name: project2-pv-pedroribeiro
          mountPath: /home/pedroribeiro/project2-pv
      restartPolicy: Never
      volumes:
      - name: project2-pv-pedroribeiro
        persistentVolumeClaim:
          claimName: project2-pvc-pedroribeiro
  backoffLimit: 4
